#!/usr/bin/env bash
# setup-labels.sh — Create Gmail labels for triage and store their IDs. (v2.5)
# Run once during setup.
#
# v2.5 changes vs v2.4:
# - gws CLI replaced with Maton API Gateway (MATON_API_KEY bearer token)
# - Fixed the jq exit code 5 bug: jq -r '... // empty' returns exit 0
#   even when the field is absent. Previously this caused set -e to abort
#   the script when LABEL_ID came back empty. Now handled with '|| true'
#   on the jq pipeline and an explicit [ -z ] check.

set -euo pipefail

export PATH="/usr/local/opt/node@22/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

DATA_DIR="${HOME}/.openclaw/workspace/data"
LABEL_IDS_FILE="${DATA_DIR}/label-ids.env"
MATON_BASE="https://gateway.maton.ai/google-mail/gmail/v1/users/me"

mkdir -p "$DATA_DIR"

LABELS=(
  "Triage/Newsletter"
  "Triage/Notification"
  "Triage/NeedsReply"
  "Triage/Review"
  "Triage/Approved"
  "Triage/Processed"
)

echo "# Gmail label ID mapping — generated by setup-labels.sh" > "$LABEL_IDS_FILE"
echo "# $(date -u)" >> "$LABEL_IDS_FILE"

for LABEL_NAME in "${LABELS[@]}"; do
  echo "Creating label: $LABEL_NAME"

  # Attempt to create via Maton (returns existing label if already present)
  RESULT=$(curl -sf -X POST \
    -H "Authorization: Bearer ${MATON_API_KEY}" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg name "$LABEL_NAME" \
      '{name:$name, labelListVisibility:"labelShow", messageListVisibility:"show"}')" \
    "${MATON_BASE}/labels" 2>&1) || RESULT=""

  # Extract label ID — use || true so set -e doesn't fire on empty output
  LABEL_ID=$(echo "$RESULT" | jq -r '.id // empty' 2>/dev/null) || LABEL_ID=""

  if [ -z "$LABEL_ID" ]; then
    # Label may already exist — list all and find by name
    echo "  Label may already exist, looking it up..."
    LIST=$(curl -sf \
      -H "Authorization: Bearer ${MATON_API_KEY}" \
      "${MATON_BASE}/labels" 2>/dev/null) || LIST="{}"
    LABEL_ID=$(echo "$LIST" | jq -r --arg name "$LABEL_NAME" \
      '.labels[] | select(.name == $name) | .id // empty' 2>/dev/null) || LABEL_ID=""
  fi

  if [ -n "$LABEL_ID" ]; then
    # Convert label name to env var: Triage/Newsletter → LABEL_TRIAGE_NEWSLETTER
    ENV_KEY=$(echo "$LABEL_NAME" | tr '[:lower:]/' '[:upper:]_' | sed 's/[^A-Z0-9_]/_/g')
    ENV_KEY="LABEL_${ENV_KEY}"
    echo "${ENV_KEY}=\"${LABEL_ID}\"" >> "$LABEL_IDS_FILE"
    echo "  OK: $LABEL_NAME → $LABEL_ID"
  else
    echo "  WARNING: Could not create or find label '$LABEL_NAME'"
  fi
done

echo ""
echo "Label IDs saved to: $LABEL_IDS_FILE"
echo "Contents:"
cat "$LABEL_IDS_FILE"
