#!/usr/bin/env bash
# setup-labels.sh — Create Gmail labels for triage and store their IDs.
# Run once during setup. Gmail API requires label IDs (not names) for
# modify operations, so we create labels and save the ID mapping.
set -euo pipefail

DATA_DIR="${HOME}/.openclaw/workspace/data"
LABEL_IDS_FILE="${DATA_DIR}/label-ids.env"
mkdir -p "$DATA_DIR"

LABELS=(
  "Triage/Newsletter"
  "Triage/Notification"
  "Triage/NeedsReply"
  "Triage/Review"
  "Triage/Approved"
  "Triage/Processed"
)

echo "# Gmail label ID mapping — generated by setup-labels.sh" > "$LABEL_IDS_FILE"
echo "# $(date -u)" >> "$LABEL_IDS_FILE"

for LABEL_NAME in "${LABELS[@]}"; do
  echo "Creating label: $LABEL_NAME"

  # Create the label via Gmail API
  RESULT=$(gws gmail users labels create \
    --params '{"userId":"me"}' \
    --json "$(jq -n --arg name "$LABEL_NAME" \
      '{name:$name, labelListVisibility:"labelShow", messageListVisibility:"show"}')" \
    2>&1) || true

  # Extract label ID from result
  LABEL_ID=$(echo "$RESULT" | jq -r '.id // empty' 2>/dev/null)

  if [ -z "$LABEL_ID" ]; then
    # Label might already exist — list all labels and find it
    echo "  Label may already exist, looking it up..."
    LABEL_ID=$(gws gmail users labels list --params '{"userId":"me"}' \
      | jq -r --arg name "$LABEL_NAME" '.labels[] | select(.name == $name) | .id // empty')
  fi

  if [ -n "$LABEL_ID" ]; then
    # Convert label name to env var format: Triage/Newsletter → LABEL_TRIAGE_NEWSLETTER
    ENV_KEY=$(echo "$LABEL_NAME" | tr '[:lower:]/' '[:upper:]_' | sed 's/[^A-Z0-9_]/_/g')
    ENV_KEY="LABEL_${ENV_KEY}"
    echo "${ENV_KEY}=\"${LABEL_ID}\"" >> "$LABEL_IDS_FILE"
    echo "  OK: $LABEL_NAME → $LABEL_ID"
  else
    echo "  WARNING: Could not create or find label '$LABEL_NAME'"
  fi
done

echo ""
echo "Label IDs saved to: $LABEL_IDS_FILE"
echo "Contents:"
cat "$LABEL_IDS_FILE"
